export const RESPONSE_CODES = {
  SUCCESS: 'RC_200',
  CREATED: 'RC_201',
  BAD_REQUEST: 'RC_400',
  UNAUTHORIZED: 'RC_401',
  FORBIDDEN: 'RC_403',
  NOT_FOUND: 'RC_404',
  USER_NOT_FOUND: 'RC_404_USER',
  INTERNAL_ERROR: 'RC_500',
  VALIDATION_ERROR: 'RC_422',
  USER_EXISTS: 'RC_409',
  INVALID_CREDENTIALS: 'RC_401_CRED',
  USER_INACTIVE: 'RC_403_INACTIVE',
  EMAIL_INVALID: 'RC_400_EMAIL',
  OTP_SENT: 'RC_200_OTP_SENT',
  EMAIL_SEND_FAILED: 'RC_500_EMAIL',
  OTP_INVALID: 'RC_400_OTP',
  OTP_EXPIRED: 'RC_400_OTP_EXP',
  OTP_ALREADY_USED: 'RC_400_OTP_USED',
  WA_NOT_CONNECTED: 'RC_503_WA',
  WA_SEND_FAILED: 'RC_500_WA',
  // OTP Email endpoints
  OTP_EMAIL_SEND_SUCCESS: 'RC_200_OTP_EMAIL_SEND',
  OTP_EMAIL_SEND_FAILED: 'RC_500_OTP_EMAIL_SEND',
  OTP_EMAIL_VERIFY_SUCCESS: 'RC_200_OTP_EMAIL_VERIFY',
  OTP_EMAIL_VERIFY_FAILED: 'RC_400_OTP_EMAIL_VERIFY',
  // Login endpoints
  LOGIN_SUCCESS: 'RC_200_LOGIN',
  LOGIN_FAILED: 'RC_401_LOGIN',
  // Register endpoints  
  REGISTER_STEP1_SUCCESS: 'RC_200_REGISTER_STEP1',
  REGISTER_STEP1_FAILED: 'RC_400_REGISTER_STEP1',
  // Registration endpoints
  REGISTER_COMPLETE_SUCCESS: 'RC_200_REGISTER_COMPLETE',
  REGISTER_COMPLETE_FAILED: 'RC_400_REGISTER_COMPLETE'
};